"""crear tablas iniciales

Revision ID: 42a96d4218fb
Revises: 
Create Date: 2026-03-18 14:27:43.736837

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '42a96d4218fb'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('zonas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=True),
    sa.Column('codigo_postal', sa.String(), nullable=True),
    sa.Column('limite_velocidad', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('patinetes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero_serie', sa.String(), nullable=True),
    sa.Column('modelo', sa.String(), nullable=True),
    sa.Column('bateria', sa.Float(), nullable=True),
    sa.Column('estado', sa.Enum('disponible', 'en_uso', 'mantenimiento', 'sin_bateria', name='estado'), nullable=True),
    sa.Column('puntuacion_usuario', sa.Float(), nullable=True),
    sa.Column('zona_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['zona_id'], ['zonas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('patinetes')
    op.drop_table('zonas')
    # ### end Alembic commands ###
